FROM python:2-alpine

LABEL maintainer="milonas.ko@gmail.com, forked: github.com/sdhamilton6/rabbitmq-alert"

RUN apk update && \
    apk add git

ADD rabbitmqalert /app

RUN pip install requests

CMD ["python", "/app/rabbitmqalert.py"]